FROM ollama/ollama
EXPOSE 11434
ENTRYPOINT ["/bin/ollama", "serve"]

# Nginx(웹서버)를 베이스로 사용
#FROM nginx:alpine

# 내가 만든 html을 Nginx 기본 폴더로 복사
#COPY index.html /usr/share/nginx/html/index.html

# 80번 포트 열기
#EXPOSE 80